openapi: "3.0.0"

info:
  title: blabla
  version: 1.0.0

paths:
  /:
    get:
      summary: Renvoie un message de bienvenue
      operationId: server.handlers.Welcome.home
      responses:
          '200':
            description: Un petit bonjour
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Greetings'
  /calculate/cas_types:
    post:
      summary: Calcule l'impact par cas types
      operationId: server.handlers.CasTypes.calculate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculateCasTypes'
      responses:
          '201':
            description: Cool !
  /calculate/revenus:
    post:
      summary: Calcule l'impact par cas types
      operationId: server.handlers.CasTypes.revenus
      responses:
          '201':
            description: Renvoie les revenus des cas types. Utilisé seulement par l'API Dash
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/revenus'
  /metadata/description_cas_types:
    post:
      summary: Decrit les cas types
      operationId: server.handlers.CasTypes.description_cas_types
      responses:
        '201':
          description: Renvoie la description des cas types par défaut
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/description_cas_types'
  /calculate/compare_old:
    post:
      summary: Calcule l'impact d'une loi
      operationId: server.handlers.SimulationRunner.compare
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/compareoldnew_old'
      responses:
          '201':
            description: Qu'est ce que c'est description
  /calculate/compare:
    post:
      summary: Calcule l'impact d'une loi
      operationId: server.handlers.SimulationRunner.simulereforme
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/compareoldnew'
      responses:
          '201':
            description: Qu'est ce que c'est description
components:
  schemas:
    Greetings:
      type: object
      properties:
        hello:
          type: string
    CalculateCasTypes:
      type: object
      properties:
        reform:
          type: object
        cas_types:
          type: array
    revenus:
      type: object
    compareoldnew_old:
      type: object
      properties:
        isdecile:
          type: boolean
        bareme_ir:
          type: object
          properties:
            seuils:
              type: array
              items:
                type: integer
            taux:
              type: array
              items:
                type: number
    compareoldnew:
      type: object
      properties:
        deciles:
          type: boolean
        reforme:
          type: object
          properties:
            impot_revenu:
              type: object
              properties:
                bareme:
                  type: object
                  properties:
                    seuils:
                      type: array
                      items:
                        type: integer
                    taux:
                      type: array
                      items:
                        type: number
                decote:
                  type: object
                  properties:
                    seuil_celib:
                      type: integer
                    seuil_couple:
                      type: integer
                    taux:
                      type: number
                plafond_qf:
                  type: object
                  properties:
                    maries_ou_pacses:
                      type: integer
                    celib_enf:
                      type: integer
                    celib:
                      type: integer
                    reduc_postplafond:
                      type: integer
                    reduc_postplafond_veuf:
                      type: integer
                    abat_dom:
                      type: object
                      properties:
                        taux_GuadMarReu:
                          type: number
                        plaf_GuadMarReu:
                          type: integer
                        taux_GuyMay:
                          type: number
                        plaf_GuyMay:
                          type: integer
                    reduction_ss_condition_revenus:
                      type: object
                      properties:
                        seuil_maj_enf:
                          type: integer
                        seuil1:
                          type: integer
                        seuil2:
                          type: integer
                        taux:
                          type: number
                abattements_rni:
                  type: object
                  properties:
                    personne_agee_ou_invalide:
                      type: object
                      properties:
                        montant_1:
                          type: integer
                        montant_2:
                          type: integer
                        plafond_1:
                          type: integer
                        plafond_2:
                          type: integer
        description_cas_types:
          type: array
          items:
            type: object
            properties:
              nombre_declarants:
                type: integer
              nombre_personnes_a_charge:
                type: integer
              nombre_declarants_retraites:
                type: integer
              revenu:
                type: integer
              guadeloupe:
                type: boolean
    description_cas_types:
      type: array
      items:
        type: object
        properties:
          nombre_declarants:
            type: integer
          nombre_personnes_a_charge:
            type: integer
          nombre_declarants_retraites:
            type: integer
          revenu:
            type: integer
          outre_mer:
            type: integer


