openapi: "3.0.0"

info:
  title: blabla
  version: 1.0.0

paths:
  /calculate/cas_types:
    post:
      summary: Calcule l'impact par cas types
      operationId: server.handlers.CasTypes.calculate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculateCasTypes'
      responses:
          '201':
            description: Cool !
  /calculate/totext:
    post:
      summary: Calcule l'impact par cas types
      operationId: server.handlers.CasTypes.totext
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/totext'
      responses:
          '201':
            description: Encore plus Cool
  /calculate/compare:
    post:
      summary: Calcule l'impact d'une loi
      operationId: server.handlers.SimulationRunner.compare
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/compareoldnew'
      responses:
          '201':
            description: Qu'est ce que c'est description

components:
  schemas:
    CalculateCasTypes:
      type: object
      properties:
        reform:
          type: object
        cas_types:
          type: array
    totext:
      type: object
      properties:
        idfoy:
          type: string
    compareoldnew:
      type: object
      properties:
        isdecile:
          type: boolean
        bareme_ir:
          type: object
          properties:
            seuils:
              type: array
              items:
                type: integer
            taux:
              type: array
              items:
                type: number