openapi: "3.0.0"

info:
  title: blabla
  version: 1.0.0

paths:
  /calculate/cas_types:
    post:
      summary: Calcule l'impact par cas types
      operationId: server.handlers.CasTypes.calculate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculateCasTypes'
      responses:
          '201':
            description: Cool !
  /calculate/revenus:
    post:
      summary: Calcule l'impact par cas types
      operationId: server.handlers.CasTypes.revenus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/revenus'
      responses:
          '201':
            description: Encore plus Cool
  /calculate/compare_old:
    post:
      summary: Calcule l'impact d'une loi
      operationId: server.handlers.SimulationRunner.compare
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/compareoldnew_old'
      responses:
          '201':
            description: Qu'est ce que c'est description
  /calculate/compare:
    post:
      summary: Calcule l'impact d'une loi
      operationId: server.handlers.SimulationRunner.simulereforme
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/compareoldnew'
      responses:
          '201':
            description: Qu'est ce que c'est description
components:
  schemas:
    CalculateCasTypes:
      type: object
      properties:
        reform:
          type: object
        cas_types:
          type: array
    revenus:
      type: object
    compareoldnew_old:
      type: object
      properties:
        isdecile:
          type: boolean
        bareme_ir:
          type: object
          properties:
            seuils:
              type: array
              items:
                type: integer
            taux:
              type: array
              items:
                type: number
    compareoldnew:
      type: object
      properties:
        deciles:
          type: boolean
        reforme:
          type: object
          properties:
            impot_revenu:
              type: object
              properties:
                bareme:
                  type: object
                  properties:
                    seuils:
                      type: array
                      items:
                        type: integer
                    taux:
                      type: array
                      items:
                        type: number
                decote:
                  type: object
                  properties:
                    seuil_celib:
                      type: integer
                    seuil_couple:
                      type: integer
